name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: github.ref
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go test -v

  build:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Get current package version
        id: current_version
        run: echo "version=$(make version)" >> $GITHUB_OUTPUT
      - uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.current_version.outputs.version }}"
          generateReleaseNotes: true
          makeLatest: true
          prerelease: false
          allowUpdates: false
          skipIfReleaseExists: true
